
import com.mysql.cj.xdevapi.Statement;
import com.mysql.jdbc.Connection;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import static java.lang.Math.random;
import static java.lang.StrictMath.random;
import java.security.SecureRandom;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.util.Random;
import javax.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsh
 */
public class add extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    public add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(855, 660));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel4.setText("DOB");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 220, 34, 17);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(597, 217, 106, 22);

        jLabel5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel5.setText("AADHAR NO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 220, 98, 17);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(126, 217, 200, 22);

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel6.setText("PHONE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 285, 52, 17);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(126, 282, 200, 22);

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel7.setText("GENDER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 350, 67, 17);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("MALE");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(126, 346, 59, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("FEMALE");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(220, 346, 73, 25);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 570, 132, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("OTHER");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(329, 346, 69, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(126, 154, 309, 22);

        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 570, 132, 25);

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel2.setText("AGE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 150, 50, 22);

        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(680, 570, 132, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(597, 154, 106, 22);

        jLabel8.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel8.setText("GMAIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(492, 285, 60, 17);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(597, 282, 197, 22);

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel9.setText("ADDRESS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(12, 404, 74, 17);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(126, 401, 550, 22);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 157, 45, 17);

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        jLabel13.setText("ADD CUSTOMER DETAILS");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(179, 29, 465, 44);

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel3.setText("YYYY/MM/DD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(710, 220, 98, 17);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 446, 853, 10);

        jLabel11.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel11.setText("CUSTOMER ID.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(12, 472, 113, 17);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(602, 469, 193, 22);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 518, 853, 10);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 814, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String na,ag,adno,dob,ph,gm,gen,add,cid;
       na=jTextField1.getText();
       ag=jTextField2.getText();
       adno=jTextField3.getText();
       dob=jTextField4.getText();
       ph=jTextField5.getText();
       gm=jTextField6.getText();
       if(jRadioButton1.isSelected()){gen="Male";}
       else if(jRadioButton2.isSelected()){gen="Female";}
       else{gen="Other";}
       add=jTextField7.getText();
       cid=jTextField8.getText();
        
       
        
        
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms","root","0000");
            java.sql.Statement stm=con.createStatement();
           String sql="insert into ad values('"+na+"','"+ag+"','"+adno+"','"+dob+"','"+ph+"','"+gm+"','"+gen+"','"+add+"','"+cid+"');";
            int rs = stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Record added");
        }
        catch (Exception e){JOptionPane.showMessageDialog(null, e);}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jTextField8.setEditable(false);        // TODO add your handling code here:
Random rand=new Random();
int num = rand.nextInt(100000);
String f = String.format("%05d", num); 
jTextField8.setText(f);
    }//GEN-LAST:event_formWindowActivated

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
 String adno=jTextField3.getText();
int l=adno.length();
char c=evt.getKeyChar();
if (l<11){jTextField3.setForeground(Color.red);}
else{jTextField3.setForeground(Color.black);
}
if(Character.isLetter(c)){jTextField3.setEditable(false);}
else{jTextField3.setEditable(true);}


            
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
 String adno=jTextField5.getText();
int l=adno.length();
char c=evt.getKeyChar();
if (l<9){jTextField5.setForeground(Color.red);}
else{jTextField5.setForeground(Color.black);
}
if(Character.isLetter(c)){jTextField5.setEditable(false);}
else{jTextField5.setEditable(true);}
       // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
home ad = new home();
            ad.show();        // TODO add your handling code here:
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
