
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsh
 */
public class shopping extends javax.swing.JFrame {

    /**
     * Creates new form shopping
     */
    public shopping() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(833, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("BILL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 83, 44);

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel2.setText("CID.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 116, 41, 22);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(108, 113, 128, 22);

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel3.setText("CUST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 110, 114, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(509, 113, 299, 22);

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel4.setText("BOOK NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(387, 213, 122, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(170, 210, 156, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 164, 849, 10);

        jLabel5.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel5.setText("BOOK CODE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 213, 124, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(550, 210, 250, 22);

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel6.setText("GENRE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 285, 67, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action and Adventure", "Classics", "Comic Book", "Graphic Novel", "Mystery", "Fantasy", "Historical Fiction", "Horror", "Literary Fiction", "Romance", "Science Fiction", "Short Stories", "Suspense and Thrillers", "Biographies & Autobiographies", "Cookbooks", "Essays", "History", "Memoir", "Poetry" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 280, 156, 22);

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel7.setText("QTY");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 363, 39, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(640, 280, 156, 22);

        jLabel8.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel8.setText("PRICE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(387, 363, 80, 22);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(170, 360, 114, 22);

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(12, 560, 163, 25);

        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(205, 560, 163, 25);

        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(620, 560, 163, 25);

        jLabel10.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel10.setText("DATE OF PURCHASE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(387, 285, 194, 22);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(680, 350, 106, 22);

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel9.setText("TOTAL");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(23, 460, 64, 22);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(170, 460, 116, 22);

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 450, 174, 25);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 412, 849, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 507, 849, 10);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 850, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
jTextField8.setEditable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String bna,dop,cid,bco,cna,gen;
int qt;
float pr,to;       
cid=jTextField1.getText();
cna = jTextField2.getText();
bco=jTextField3.getText();
bna=jTextField4.getText();
dop=jTextField5.getText();
qt=Integer.parseInt(jTextField6.getText());
gen=(String)jComboBox1.getSelectedItem().toString();
pr=Float.parseFloat(jTextField7.getText());
to=Float.parseFloat(jTextField8.getText());

        
       
        
        
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms","root","0000");
            java.sql.Statement stm=con.createStatement();
           String sql="insert into ord values('"+cna+"','"+cid+"','"+bco+"','"+bna+"','"+gen+"','"+dop+"',"+qt+","+pr+","+to+");";
            int rs = stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Record added");
        }
        catch (Exception e){JOptionPane.showMessageDialog(null, e);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
home hp = new home();
            hp.show();        // TODO add your handling code here:
dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int qt=Integer.parseInt(jTextField6.getText());        // TODO add your handling code here:
        float pr,to;
        pr=Float.parseFloat(jTextField7.getText());
        to=qt*pr;
        jTextField8.setText(""+to);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shopping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shopping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
